### Ürün ve Pazar

* Ali, Veli, Ayşe bazı meyve çeşitleri topluyor. Nar, Kiraz, Karpuz toplasınlar
* İki farklı pazarda satma ihtimalleri var. Pazarların
        * Meyvelere sırayla verilen fiyatlar (Nar, Kiraz, Karpuz)
            * Pazar 1: 5, 3, 8 tl
            * Pazar 2: 4, 5, 9 tl
* Kişilerin pazarlardaki muhtemel kazançlarını inceleyelim.
* Ürünlerin pazarlardaki muhtemel kazançlarını inceleyelim.
* 250 tl altında kazanç olan kaç alternatif var.

In [1]:
import numpy as np
import random as rnd

#### Veri türelim

In [2]:
pazar = {
            "pazar1":{"Nar":5, "Kiraz":3, "Karpuz":8},
            "pazar2":{"Nar":4, "Kiraz":5, "Karpuz":9}
        }
#
pazar

{'pazar1': {'Nar': 5, 'Kiraz': 3, 'Karpuz': 8},
 'pazar2': {'Nar': 4, 'Kiraz': 5, 'Karpuz': 9}}

In [3]:
kisiler = ["Ali","Veli","Ayşe"]
meyveler = ["Nar","Kiraz","Karpuz"]

#
efor = dict()
for kisi in kisiler:
    sepet = dict()
    for meyve in meyveler:
        sepet[meyve] = rnd.randint(0,500)
    efor[kisi] = sepet

#---
efor

{'Ali': {'Nar': 214, 'Kiraz': 153, 'Karpuz': 334},
 'Veli': {'Nar': 106, 'Kiraz': 447, 'Karpuz': 68},
 'Ayşe': {'Nar': 340, 'Kiraz': 218, 'Karpuz': 110}}

### Matrix formuna çevirelim

#### Pazar

In [13]:
pazarFiyatlari = [list(p.values()) for p in pazar.values()]
pazarFiyatlari

[[5, 3, 8], [4, 5, 9]]

In [15]:
array_pazar = np.vstack(pazarFiyatlari)
array_pazar

array([[5, 3, 8],
       [4, 5, 9]])

#### Efor

In [19]:
eforAdetleri = [list(e.values()) for e in efor.values()]
eforAdetleri

[[214, 153, 334], [106, 447, 68], [340, 218, 110]]

In [20]:
array_efor = np.vstack(eforAdetleri)
array_efor

array([[214, 153, 334],
       [106, 447,  68],
       [340, 218, 110]])

#### Kazanç Hesaplama

In [25]:
array_efor.shape #(3, 3)
array_pazar.shape #(2, 3)
array_pazar.T.shape #(3,2) #tranpose

#dot product (3,3) * (3,2) = (3,2)
hesaplama = array_efor.dot(array_pazar.T)
hesaplama

array([[4201, 4627],
       [2415, 3271],
       [3234, 3440]])

##### Sonuçları dict olarak tutalım.

In [36]:
#pazarKazanclari = dict()

#pazarKazanclari["pazar1"] = dict(zip(meyveler, hesaplama[:,0]))
#pazarKazanclari["pazar1"] = dict(zip(meyveler, hesaplama[:,1]))

#------------------------------------------------------
#
pazarKazanclari = dict([ 
                        ("pazar1", dict(zip(meyveler, hesaplama[:,0]))),
                        ("pazar2", dict(zip(meyveler, hesaplama[:,1])))
                      ])


pazarKazanclari

{'pazar1': {'Nar': 4201, 'Kiraz': 2415, 'Karpuz': 3234},
 'pazar2': {'Nar': 4627, 'Kiraz': 3271, 'Karpuz': 3440}}

In [57]:
print("{:>5}{:>15}{:>15}".format(*meyveler)) #{:>5.2s} ile metinsel alanda kaç karekter gösterilecek.
print("-"*37)
print("{:>5,}{:>15,}{:>15,}".format(*pazarKazanclari["pazar1"].values()))
print("{:>5,}{:>15,}{:>15,}".format(*pazarKazanclari["pazar2"].values()))

  Nar          Kiraz         Karpuz
-------------------------------------
4,201          2,415          3,234
4,627          3,271          3,440


#### Filtreler Verelim

In [66]:
p_dizi = np.vstack([list(p.values()) for p in pazarKazanclari.values()]).T #transpose
p_dizi 

array([[4201, 4627],
       [2415, 3271],
       [3234, 3440]])

In [70]:
#pazarların toplam kazancı nedir?
p_dizi.sum(axis=0) #satır boyunca işlem yapar

print(f"Pazar 1: {p_dizi.sum(axis=0)[0] :,} tl")
print(f"Pazar 2: {p_dizi.sum(axis=0)[1] :,} tl")

Pazar 1: 9,850 tl
Pazar 2: 11,338 tl


In [82]:
#3000 üzerinde olan kazançları getirelim.
filtre_35K = p_dizi > 3000
p_dizi[filtre_35K]


#--
np.count_nonzero(filtre_35K) #şarta uyanların adedi #0 ve yokluk False olarak değerlendirilir.

#
filtre_35K.sum()
filtre_35K.sum(axis=0) #pazar bazlı şarta uyanlar

#
filtre_35K.any(axis=0) #hiç şarta uyan var mı?
filtre_35K.all(axis=0) #hepsi uyuyor mu?

array([False,  True])